version: "3.9"
services:
  db:
    image: postgres:12-alpine
    container_name: bankDB
    restart: always
    env_file: 
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres/data
    hostname:  host.docker.internal

  bank:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
     - 8080:8080
    environment:
      - DB_SOURCE=postgresql://root:123@localhost:5432/simple_bank?sslmode=disable
    hostname: localhost

volumes:
  db:
  db-auth:
